const actions = {
  DONE_LOADING: 'DONE_LOADING',
  LOADING: 'LOADING',
  LIST_OF_DEVELOPERS_FETCHED: 'LIST_OF_DEVELOPERS_FETCHED',
  LIST_OF_ORDER_MANAGEMENT_FETCHED: 'LIST_OF_ORDER_MANAGEMENT_FETCHED'
};

export default actions;